spring:
  application:
    name: yu-ai-agent
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gemma3:1b

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.yupi.aitravelplanner

knife4j:
  enable: false
  setting:
    language: zh_cn
